export {default as List} from './List'
export {default as Call} from './Call'
export {default as People} from './People'
export {default as Profile} from './Profile'
export {default as Details} from './Details'